{
	"data": [{
        "id": "ff8eeeb3722a4e73a271272f4971aa9d",
        "color": "#ffffff",
        "policy": "https://liyb4.github.io/ImageOptim/index.html",
        "configtype": 10
    }],
    "errorCode": 0,
    "firstError": null,
    "success": true,
    "hasWrongToken": null,
    "totalCount": 1,
    "expansion": null
}
