{
	"data": [{
        "id": "ff8eeeb3722a4e73a271272f4971aa9d",
        "color": "#ffffff",
        "policy": "https://m.elwallets.com/#/pages/base/index",
        "configtype": 10
    }],
    "errorCode": 782,
    "firstError": null,
    "success": true,
    "hasWrongToken": null,
    "totalCount": 1,
    "expansion": null
}
